fix: upgrade aws-sdk, Mux elements (#221)
* fix: upgrade aws-sdk, Mux elements

* fix: upgrade rest of packages
@types/react and tsx needed a locked version because the types
would not be compatible with Mux elements older React types
and the newer tsx was breaking test coverage

* fix: downgrade undici to 5
broke Next.js builds
../../node_modules/undici/lib/web/fetch/util.js
Module parse failed: Unexpected token (884:57)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|       // 5. If object is not a default iterator object for interface,
|       //    then throw a TypeError.
>       if (typeof this !== 'object' || this === null || !(#target in this)) {
|         throw new TypeError(
|           `'next' called on an object that does not implement interface ${name} Iterator.`

Import trace for requested module:
../../node_modules/undici/lib/web/fetch/util.js
../../node_modules/undici/lib/web/fetch/formdata.js
../../node_modules/undici/index.js
../../dist/providers/vercel-blob/provider.js
../../dist/providers/providers.js
../../dist/handlers/local-upload.js
../../dist/process.js
../../dist/request-handler.js
./app/api/video/route.js
> Build failed because of webpack errors

* chore: add amazon s3 example config in comments